# Generated by Django 4.1.5 on 2023-03-12 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='nzme',
            new_name='name',
        ),
    ]
